#######################################################################################
# Book settings
title: ''
author: Berkeley DSEP
email: ''
logo                        : "favicon.png"  # A path to the book logo
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "favicon.png"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  google_analytics_id       : "UA-148221575-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://inferentialthinking.org"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

#######################################################################################
# Launch button settings
launch_buttons:
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  use_repository_button     : true
  use_edit_page_button     : true
  use_issues_button     : true

repository:
  url                       : https://github.com/data-8/textbook  # The URL to your book's repository
